// ─── ArchiAI — Presets, Archetypes & Plot Shapes ────────────────────────────
// Data file for the preset browser. Three collections:
//   VASTU_PRESETS  – 15 standard residential layouts
//   ARCHETYPES     – 6 regional Indian architectural traditions
//   PLOT_SHAPES    – 4 special plot-shape scenarios with Vastu guidance

// ─── VASTU_PRESETS ────────────────────────────────────────────────────────────
export const VASTU_PRESETS = [
  // ── Micro plots ────────────────────────────────────────────────────────────
  {
    id: "micro-north-1bhk",
    name: "Compact Studio North",
    subtitle: "20×30 ft · 1 BHK · North-facing starter home",
    tag: null,
    plotW: 20,
    plotH: 30,
    bhk: 1,
    facing: "North",
    city: "GHMC (Hyderabad)",
    budget: "Economy (₹20-40L)",
    floors: 1,
    area: 600,
    vastuScore: 81,
    estCost: "₹18–24 L",
    highlights: [
      "Open NE corner for morning light & positive energy",
      "Compact kitchen in SE, living space faces North road",
      "Maximum usable area on tight 20 ft width",
    ],
    category: "standard",
  },
  {
    id: "micro-east-2bhk",
    name: "East-Light Duplex Micro",
    subtitle: "20×40 ft · 2 BHK · East-facing — ideal sunrise orientation",
    tag: "Best Seller",
    plotW: 20,
    plotH: 40,
    bhk: 2,
    facing: "East",
    city: "CMDA (Chennai)",
    budget: "Economy (₹20-40L)",
    floors: 2,
    area: 800,
    vastuScore: 88,
    estCost: "₹28–36 L",
    highlights: [
      "East entrance captures auspicious morning sun",
      "Master bedroom in SW, children's room in W on upper floor",
      "Puja alcove in NE corner — highest Vastu compliance zone",
    ],
    category: "standard",
  },
  {
    id: "micro-north-2bhk-25x40",
    name: "Narrow North Nest",
    subtitle: "25×40 ft · 2 BHK · North-facing compact family home",
    tag: null,
    plotW: 25,
    plotH: 40,
    bhk: 2,
    facing: "North",
    city: "PMC (Pune)",
    budget: "Economy (₹20-40L)",
    floors: 1,
    area: 1000,
    vastuScore: 85,
    estCost: "₹30–40 L",
    highlights: [
      "North road access keeps NE corner fully open",
      "In-line kitchen and dining along SE–SW axis",
      "Side setbacks on both east and west retained as utility zones",
    ],
    category: "standard",
  },

  // ── Small plots ─────────────────────────────────────────────────────────────
  {
    id: "small-east-3bhk-30x40",
    name: "Classic East 3BHK",
    subtitle: "30×40 ft · 3 BHK · East-facing — most popular layout",
    tag: "Best Seller",
    plotW: 30,
    plotH: 40,
    bhk: 3,
    facing: "East",
    city: "BBMP (Bengaluru)",
    budget: "Lower-Premium (₹40-60L)",
    floors: 2,
    area: 1200,
    vastuScore: 91,
    estCost: "₹48–58 L",
    highlights: [
      "East entrance with NE puja room — textbook Vastu compliance",
      "Two bedrooms on upper floor, master on SW ground floor",
      "Car porch in SE, utility in NW — both Vastu-correct zones",
    ],
    category: "standard",
  },
  {
    id: "small-north-3bhk-30x40",
    name: "North Avenue 3BHK",
    subtitle: "30×40 ft · 3 BHK · North-facing — business & prosperity axis",
    tag: null,
    plotW: 30,
    plotH: 40,
    bhk: 3,
    facing: "North",
    city: "MCD (Delhi)",
    budget: "Lower-Premium (₹40-60L)",
    floors: 2,
    area: 1200,
    vastuScore: 89,
    estCost: "₹52–62 L",
    highlights: [
      "North-facing entrance aligned with Kubera (wealth) direction",
      "Study/work room in NE maximises mental clarity per Vastu",
      "Generous living area in north wing catches prevailing breeze",
    ],
    category: "standard",
  },
  {
    id: "small-east-3bhk-30x50",
    name: "Garden East 3BHK",
    subtitle: "30×50 ft · 3 BHK · East-facing with front lawn space",
    tag: null,
    plotW: 30,
    plotH: 50,
    bhk: 3,
    facing: "East",
    city: "BBMP (Bengaluru)",
    budget: "Lower-Premium (₹40-60L)",
    floors: 2,
    area: 1500,
    vastuScore: 90,
    estCost: "₹55–68 L",
    highlights: [
      "Extra depth allows NE garden courtyard to stay fully open",
      "Separate formal living and family room on ground floor",
      "Rear (west) side used for store and utility — correct Vastu placement",
    ],
    category: "standard",
  },
  {
    id: "small-north-4bhk-30x50",
    name: "North Premium 4BHK",
    subtitle: "30×50 ft · 4 BHK · North-facing — growing family layout",
    tag: "Best Seller",
    plotW: 30,
    plotH: 50,
    bhk: 4,
    facing: "North",
    city: "PMC (Pune)",
    budget: "Premium (₹60-100L)",
    floors: 3,
    area: 1800,
    vastuScore: 86,
    estCost: "₹72–90 L",
    highlights: [
      "Three-storey allows master + 3 bedrooms with Vastu-correct placement",
      "Terrace garden on top keeps SW heavy — balances energy mass",
      "Open NE balcony on each floor brings light into deep plot",
    ],
    category: "standard",
  },

  // ── Medium plots ────────────────────────────────────────────────────────────
  {
    id: "med-east-3bhk-40x50",
    name: "Spacious East Villa",
    subtitle: "40×50 ft · 3 BHK · East-facing single-storey bungalow",
    tag: null,
    plotW: 40,
    plotH: 50,
    bhk: 3,
    facing: "East",
    city: "CMDA (Chennai)",
    budget: "Premium (₹60-100L)",
    floors: 1,
    area: 2000,
    vastuScore: 93,
    estCost: "₹68–85 L",
    highlights: [
      "Single storey preserves low SW mass, ideal Vastu energy profile",
      "Internal courtyard in Brahmasthan left open for cross-ventilation",
      "Wraparound verandah on north and east sides for passive cooling",
    ],
    category: "standard",
  },
  {
    id: "med-north-4bhk-40x60",
    name: "North Grand 4BHK",
    subtitle: "40×60 ft · 4 BHK · North-facing — premium double-storey",
    tag: "Best Seller",
    plotW: 40,
    plotH: 60,
    bhk: 4,
    facing: "North",
    city: "BMC (Mumbai)",
    budget: "Premium (₹60-100L)",
    floors: 2,
    area: 2400,
    vastuScore: 92,
    estCost: "₹88–1.05 Cr",
    highlights: [
      "Wide north frontage allows grand entrance with sunken forecourt",
      "SW master suite is elevated and heavier — perfect Vastu mass",
      "Home office in NE corner, aligned with study and learning energy",
    ],
    category: "standard",
  },
  {
    id: "med-east-5bhk-40x60",
    name: "East Luxury 5BHK",
    subtitle: "40×60 ft · 5 BHK · East-facing — large family home",
    tag: null,
    plotW: 40,
    plotH: 60,
    bhk: 5,
    facing: "East",
    city: "GHMC (Hyderabad)",
    budget: "Luxury (₹1Cr+)",
    floors: 3,
    area: 3000,
    vastuScore: 87,
    estCost: "₹1.10–1.40 Cr",
    highlights: [
      "Five bedrooms spread across three floors with Vastu zone mapping",
      "Lift core placed in SW quadrant — dead load aligns with Vastu mass",
      "Rooftop lounge in NW with overhead water tank in SW — both correct",
    ],
    category: "standard",
  },

  // ── Large plots ──────────────────────────────────────────────────────────────
  {
    id: "large-north-4bhk-50x60",
    name: "North Estate 4BHK",
    subtitle: "50×60 ft · 4 BHK · North-facing — sprawling bungalow",
    tag: null,
    plotW: 50,
    plotH: 60,
    bhk: 4,
    facing: "North",
    city: "MCD (Delhi)",
    budget: "Luxury (₹1Cr+)",
    floors: 2,
    area: 3000,
    vastuScore: 94,
    estCost: "₹1.20–1.55 Cr",
    highlights: [
      "Generous setbacks on all sides retain Vastu buffer zones intact",
      "Dedicated puja room, study, and home theatre — all Vastu-placed",
      "Central Brahmasthan forms a skylit atrium uniting both floors",
    ],
    category: "standard",
  },
  {
    id: "large-east-3bhk-50x80",
    name: "East Farmhouse 3BHK",
    subtitle: "50×80 ft · 3 BHK · East-facing — resort-style bungalow",
    tag: null,
    plotW: 50,
    plotH: 80,
    bhk: 3,
    facing: "East",
    city: "NBC (Generic)",
    budget: "Luxury (₹1Cr+)",
    floors: 1,
    area: 4000,
    vastuScore: 95,
    estCost: "₹1.30–1.70 Cr",
    highlights: [
      "Single storey on large plot achieves near-perfect Vastu compliance",
      "East-facing pool in NE quadrant energises the entire property",
      "Large SW garden berm acts as natural Vastu anchor and privacy screen",
    ],
    category: "standard",
  },
  {
    id: "large-west-4bhk-60x40",
    name: "West Court 4BHK",
    subtitle: "60×40 ft · 4 BHK · West-facing — Vastu-corrected layout",
    tag: null,
    plotW: 60,
    plotH: 40,
    bhk: 4,
    facing: "West",
    city: "BBMP (Bengaluru)",
    budget: "Premium (₹60-100L)",
    floors: 2,
    area: 2400,
    vastuScore: 80,
    estCost: "₹92–1.10 Cr",
    highlights: [
      "West entrance offset to NW quadrant minimises Vastu dosha",
      "Heavy compound wall on west side offsets evening radiation",
      "NE water feature and puja room restore elemental balance",
    ],
    category: "standard",
  },
  {
    id: "large-north-5bhk-40x80",
    name: "Deep North Manor 5BHK",
    subtitle: "40×80 ft · 5 BHK · North-facing — deep-plot luxury home",
    tag: "Best Seller",
    plotW: 40,
    plotH: 80,
    bhk: 5,
    facing: "North",
    city: "BMC (Mumbai)",
    budget: "Luxury (₹1Cr+)",
    floors: 3,
    area: 4200,
    vastuScore: 89,
    estCost: "₹1.60–2.10 Cr",
    highlights: [
      "Deep plot divided into public (N), living (C), and private (S) zones",
      "Guest suite on ground floor NW, family bedrooms on upper SW floors",
      "Sky garden on topmost slab cools the building passively",
    ],
    category: "standard",
  },
  {
    id: "large-east-4bhk-60x60",
    name: "Square East Mansion 4BHK",
    subtitle: "60×60 ft · 4 BHK · East-facing — perfect square proportions",
    tag: "Best Seller",
    plotW: 60,
    plotH: 60,
    bhk: 4,
    facing: "East",
    city: "GHMC (Hyderabad)",
    budget: "Luxury (₹1Cr+)",
    floors: 2,
    area: 3600,
    vastuScore: 96,
    estCost: "₹1.45–1.80 Cr",
    highlights: [
      "Square plot is most auspicious in Vastu — equal pada grid alignment",
      "Central Brahmasthan forms a double-height skylit hall",
      "All four wings correctly assigned to Vastu zones with no compromise",
    ],
    category: "standard",
  },
];

// ─── ARCHETYPES ───────────────────────────────────────────────────────────────
export const ARCHETYPES = [
  {
    id: "archetype-nalukettu",
    name: "Kerala Nalukettu",
    subtitle: "60×60 ft · 4 BHK · East-facing — traditional central courtyard house",
    origin: "Kerala",
    icon: "🏛️",
    plotW: 60,
    plotH: 60,
    bhk: 4,
    facing: "East",
    city: "NBC (Generic)",
    budget: "Luxury (₹1Cr+)",
    floors: 1,
    area: 3600,
    vastuScore: 97,
    estCost: "₹1.80–2.40 Cr",
    culturalNote:
      "The Nalukettu ('four buildings') is Kerala's most revered domestic form, built around the Nadumuttam — an open central courtyard that serves as the cosmic axis (Brahmasthan) of the home. Vastu Vidya and Thachu Shastra (the Kerala science of carpentry and architecture) prescribe exact proportions for each of the four wings: thekkini (south), vadakkeini (north), kizhakkeini (east), and padinjattaini (west). The central sky opening aligns the family's daily rituals with solar movement and monsoon rhythms, making it one of the most climatically and spiritually calibrated house forms in Asia.",
    features: [
      "Nadumuttam (open central courtyard) as the living spiritual core",
      "Sloping Mangalore-tile roof with deep overhangs for monsoon shedding",
      "Thulasithara (sacred basil platform) in NE corner of the courtyard",
    ],
    highlights: [
      "Nadumuttam (open central courtyard) as the living spiritual core",
      "Sloping Mangalore-tile roof with deep overhangs for monsoon shedding",
      "Thulasithara (sacred basil platform) in NE corner of the courtyard",
    ],
    category: "archetype",
  },
  {
    id: "archetype-haveli",
    name: "Rajasthani Haveli Compact",
    subtitle: "40×60 ft · 3 BHK · East-facing — enclosed courtyard with jharokhas",
    origin: "Rajasthan",
    icon: "🕌",
    plotW: 40,
    plotH: 60,
    bhk: 3,
    facing: "East",
    city: "NBC (Generic)",
    budget: "Premium (₹60-100L)",
    floors: 2,
    area: 2400,
    vastuScore: 88,
    estCost: "₹95 L–1.20 Cr",
    culturalNote:
      "The Rajasthani Haveli evolved as a fortified merchant dwelling that turned its face inward — a private world of shade, carved stone screens (jaali), and overhanging jharokha balconies that let women observe the street while remaining unseen. Vastu principles shaped the internal courtyard (chowk) as a communal breathing space, with the family shrine always placed in the northeastern room receiving first morning light. The thick lime-plastered sandstone walls provide exceptional thermal mass, keeping interiors naturally 8–12 °C cooler than outside during Rajasthan's extreme summers.",
    features: [
      "Jharokha oriel windows on upper floor with perforated stone jaali screens",
      "Enclosed inner chowk (courtyard) as both social and Vastu energy centre",
      "Arched gateway (darwaza) with heavy timber doors and brass nail art",
    ],
    highlights: [
      "Jharokha oriel windows on upper floor with perforated stone jaali screens",
      "Enclosed inner chowk (courtyard) as both social and Vastu energy centre",
      "Arched gateway (darwaza) with heavy timber doors and brass nail art",
    ],
    category: "archetype",
  },
  {
    id: "archetype-thakurbarir",
    name: "Bengali Thakurbarir",
    subtitle: "50×70 ft · 4 BHK · North-facing — multi-room zamindari compound",
    origin: "West Bengal",
    icon: "🏯",
    plotW: 50,
    plotH: 70,
    bhk: 4,
    facing: "North",
    city: "NBC (Generic)",
    budget: "Luxury (₹1Cr+)",
    floors: 2,
    area: 3500,
    vastuScore: 85,
    estCost: "₹1.30–1.70 Cr",
    culturalNote:
      "The Thakurbarir (literally 'God's house') is the ancestral compound of Bengal's zamindar (landowner) families, organised as a series of inner courtyards progressing from the semi-public natmandir (dance/worship pavilion) to the deeply private antahpur (women's quarters). Vastu zoning is expressed through a strict separation of male/public (bahirmahal) and female/private (antahpur) domains, mirroring the cosmological division of the Vastu Purusha Mandala. The north-facing orientation aligns the main Durga puja altar with the auspicious Uttara (north) direction, sacred to Kubera and Soma.",
    features: [
      "Natmandir open-pillared pavilion for Durga Puja and cultural gatherings",
      "Antahpur inner courtyard exclusively for women's domestic activities",
      "Terracotta panel friezes depicting mythological scenes on exterior walls",
    ],
    highlights: [
      "Natmandir open-pillared pavilion for Durga Puja and cultural gatherings",
      "Antahpur inner courtyard exclusively for women's domestic activities",
      "Terracotta panel friezes depicting mythological scenes on exterior walls",
    ],
    category: "archetype",
  },
  {
    id: "archetype-chettinad",
    name: "Chettinad Mansion Compact",
    subtitle: "40×80 ft · 4 BHK · East-facing — columned verandah with lime plaster",
    origin: "Tamil Nadu",
    icon: "🏠",
    plotW: 40,
    plotH: 80,
    bhk: 4,
    facing: "East",
    city: "NBC (Generic)",
    budget: "Luxury (₹1Cr+)",
    floors: 2,
    area: 3200,
    vastuScore: 92,
    estCost: "₹1.40–1.85 Cr",
    culturalNote:
      "Chettinad mansions were built by the wealthy Nattukotai Chettiar trading community using materials imported from across their global trade routes — Burmese teak columns, Italian marble floors, Belgian glasswork, and local Athangudi tiles — yet their spatial organisation is strictly Agamic: a sequence of thinnai (front verandah), courtyard, pillared hall, and private rooms aligned on a deep east–west axis. The use of egg white, lime, jaggery, and river sand in wall plaster creates the legendary cool surface finish that reduces interior temperatures by 6–8 °C. Vastu prescribes the east entrance to receive the first ray of Surya (sun god), energising the entire linear layout.",
    features: [
      "Thinnai (raised front verandah) of polished Athangudi tile as transitional public space",
      "Burmese teak columns and Athangudi tile floors with geometric patterns",
      "Lime-jaggery-egg plaster walls with lustrous finish for natural cooling",
    ],
    highlights: [
      "Thinnai (raised front verandah) of polished Athangudi tile as transitional public space",
      "Burmese teak columns and Athangudi tile floors with geometric patterns",
      "Lime-jaggery-egg plaster walls with lustrous finish for natural cooling",
    ],
    category: "archetype",
  },
  {
    id: "archetype-goan-colonial",
    name: "Goan Colonial",
    subtitle: "30×50 ft · 3 BHK · West-facing — arched windows with azulejo concept",
    origin: "Goa",
    icon: "🏘️",
    plotW: 30,
    plotH: 50,
    bhk: 3,
    facing: "West",
    city: "NBC (Generic)",
    budget: "Premium (₹60-100L)",
    floors: 2,
    area: 1500,
    vastuScore: 78,
    estCost: "₹85 L–1.05 Cr",
    culturalNote:
      "The Goan Colonial house is a unique synthesis of Portuguese Baroque architecture with indigenous Konkan building traditions — arched verandahs, oyster-shell windows (janelas), and azulejo (hand-painted tile) panels meet local laterite stone walls and a central balcão (social verandah) that mediates between the street and the home. Vastu adaptations for west-facing plots are embedded in the original design: a heavy compound wall and tall trees on the western boundary reduce afternoon heat, while an internal chapel or prayer alcove is always placed to receive eastern morning light even in a west-facing house. The patterned tile forecourt and whitewashed lime exterior reflect tropical solar radiation, making these homes remarkably cool in Goa's humid climate.",
    features: [
      "Balcão covered front verandah with wrought-iron railings as social threshold",
      "Arched Portuguese-style windows with painted azulejo tile surround panels",
      "Interior chapel or oratório (prayer niche) in NE corner receiving morning light",
    ],
    highlights: [
      "Balcão covered front verandah with wrought-iron railings as social threshold",
      "Arched Portuguese-style windows with painted azulejo tile surround panels",
      "Interior chapel or oratório (prayer niche) in NE corner receiving morning light",
    ],
    category: "archetype",
  },
  {
    id: "archetype-punjabi-kothi",
    name: "Punjabi Kothi",
    subtitle: "50×60 ft · 4 BHK · North-facing — double-height entrance & large kitchen",
    origin: "Punjab",
    icon: "🏡",
    plotW: 50,
    plotH: 60,
    bhk: 4,
    facing: "North",
    city: "NBC (Generic)",
    budget: "Luxury (₹1Cr+)",
    floors: 2,
    area: 3000,
    vastuScore: 86,
    estCost: "₹1.25–1.65 Cr",
    culturalNote:
      "The Punjabi Kothi is an expression of the community's celebratory relationship with space and abundance — a large, extrovert house with a double-height entrance porch (portico), generous interior volumes, and a kitchen-cum-dining zone that is deliberately oversized to accommodate extended family gatherings and the culture's celebrated hospitality. Vastu principles are applied through the north-facing entrance (aligning with the wealth axis), a heavy south and west boundary wall, and the placement of the family shrine in the northeast room closest to the main entrance. The rooftop terrace is considered a sacred informal space used for Lohri celebrations and summer sleeping, kept open in the northwest for cross-ventilation.",
    features: [
      "Double-height grand portico with decorative pilasters and bold colour scheme",
      "Oversized kitchen and dining area in SE wing designed for large gatherings",
      "Rooftop terrace with parapet gardens used for Lohri and seasonal celebrations",
    ],
    highlights: [
      "Double-height grand portico with decorative pilasters and bold colour scheme",
      "Oversized kitchen and dining area in SE wing designed for large gatherings",
      "Rooftop terrace with parapet gardens used for Lohri and seasonal celebrations",
    ],
    category: "archetype",
  },
];

// ─── PLOT_SHAPES ──────────────────────────────────────────────────────────────
export const PLOT_SHAPES = [
  {
    id: "shape-corner-ne",
    name: "Corner Plot N+E Roads",
    subtitle: "40×60 ft · 3 BHK · North-facing — dual road access, most auspicious",
    icon: "⌐",
    plotW: 40,
    plotH: 60,
    bhk: 3,
    facing: "North",
    city: "BBMP (Bengaluru)",
    budget: "Lower-Premium (₹40-60L)",
    floors: 2,
    area: 2400,
    vastuScore: 95,
    estCost: "₹58–72 L",
    vastuNote:
      "A corner plot with roads on both the North and East sides is considered the most auspicious configuration in Vastu Shastra, as both these directions are governed by beneficial planets (Mercury/Kubera for North, Sun/Indra for East). The plot naturally achieves an open NE quadrant — the Ishanya corner — which amplifies positive energy flow without any corrective measures.",
    adjustments: [
      "Keep the NE corner completely open — no compound wall, just a low hedge or railing to maximise energy flow",
      "Place the main entrance on the North road; secondary service entrance can be on the East road for deliveries",
      "Ensure the SW corner carries the maximum built mass (master bedroom, staircase) to anchor the property's energy",
    ],
    highlights: [
      "Keep the NE corner completely open — no compound wall, just a low hedge or railing to maximise energy flow",
      "Place the main entrance on the North road; secondary service entrance can be on the East road for deliveries",
      "Ensure the SW corner carries the maximum built mass (master bedroom, staircase) to anchor the property's energy",
    ],
    category: "shape",
  },
  {
    id: "shape-t-junction",
    name: "T-Junction Facing",
    subtitle: "30×50 ft · 3 BHK · North-facing — road pointing at plot, Veedhi Shoola remedies",
    icon: "⊥",
    plotW: 30,
    plotH: 50,
    bhk: 3,
    facing: "North",
    city: "BBMP (Bengaluru)",
    budget: "Lower-Premium (₹40-60L)",
    floors: 2,
    area: 1500,
    vastuScore: 72,
    estCost: "₹48–60 L",
    vastuNote:
      "A T-junction (called Veedhi Shoola — 'road arrow') where a road directly faces the main entrance is considered inauspicious in Vastu as it channels accelerated, concentrated energy (sha chi) straight at the property. However, when the T-junction approaches from the North or East, the negative impact is significantly reduced and manageable with standard remedies.",
    adjustments: [
      "Install a solid compound wall with a recessed gateway so the entrance door is not directly visible from the road end",
      "Plant a row of dense shrubs or erect a Vastu screen wall (Vastu Vedhi) perpendicular to the incoming road to deflect energy",
      "Place a Vastu pyramid or copper plate beneath the entrance threshold and a convex mirror above the gate to redirect incoming energy",
    ],
    highlights: [
      "Install a solid compound wall with a recessed gateway so the entrance door is not directly visible from the road end",
      "Plant a row of dense shrubs or erect a Vastu screen wall (Vastu Vedhi) perpendicular to the incoming road to deflect energy",
      "Place a Vastu pyramid or copper plate beneath the entrance threshold and a convex mirror above the gate to redirect incoming energy",
    ],
    category: "shape",
  },
  {
    id: "shape-south-corrected",
    name: "South-Facing Corrected",
    subtitle: "30×40 ft · 3 BHK · South-facing — Vastu corrections applied throughout",
    icon: "S↑",
    plotW: 30,
    plotH: 40,
    bhk: 3,
    facing: "South",
    city: "BBMP (Bengaluru)",
    budget: "Lower-Premium (₹40-60L)",
    floors: 2,
    area: 1200,
    vastuScore: 76,
    estCost: "₹42–54 L",
    vastuNote:
      "South-facing plots are often avoided due to association with Yama (the god of death) and excessive afternoon heat, but Vastu Shastra does not declare them inauspicious outright — it specifies that a south entrance must be offset to the SE quadrant (Agneya) and balanced with a set of precise remedial measures. When correctly executed, a south-facing home can achieve good Vastu compliance and is particularly suitable for those born under certain nakshatras.",
    adjustments: [
      "Offset the main entrance door to the South-East (Agneya) quadrant — never centre it on the south wall",
      "Build a taller compound wall on the south side and keep the north compound lower to allow Vastu energy to enter from the rear",
      "Place heavy landscaping (large trees or boulders) in the SW corner of the plot and keep the NE corner of the interior courtyard or garden open and uncluttered",
    ],
    highlights: [
      "Offset the main entrance door to the South-East (Agneya) quadrant — never centre it on the south wall",
      "Build a taller compound wall on the south side and keep the north compound lower to allow Vastu energy to enter from the rear",
      "Place heavy landscaping (large trees or boulders) in the SW corner of the plot and keep the NE corner of the interior courtyard or garden open and uncluttered",
    ],
    category: "shape",
  },
  {
    id: "shape-narrow-deep",
    name: "Narrow-Deep Plot",
    subtitle: "20×60 ft · 2 BHK · North-facing — elongated plot, linear room arrangement",
    icon: "▯",
    plotW: 20,
    plotH: 60,
    bhk: 2,
    facing: "North",
    city: "BBMP (Bengaluru)",
    budget: "Lower-Premium (₹40-60L)",
    floors: 2,
    area: 1200,
    vastuScore: 74,
    estCost: "₹40–52 L",
    vastuNote:
      "A narrow-deep plot (width-to-depth ratio greater than 1:2.5) presents specific challenges for Vastu: the elongated shape can cause energy to stagnate in the deep south portion while moving too rapidly through the shallow north. Vastu Shastra recommends a linear room sequence that correctly zones each depth band — public to private front to back — and uses light wells to prevent the rear of the house from becoming dark and energy-depleted.",
    adjustments: [
      "Organise rooms in a strict linear sequence: living (north) → dining & kitchen (centre) → bedrooms (south rear), keeping functions in correct Vastu zones despite the narrow width",
      "Introduce a narrow internal light well or slot skylight in the middle third of the plan to prevent the Brahmasthan zone from becoming dark and stagnant",
      "Use the full 20 ft width for each room rather than creating a central corridor — a side-access staircase along the east or west boundary wall preserves usable floor area",
    ],
    highlights: [
      "Organise rooms in a strict linear sequence: living (north) → dining & kitchen (centre) → bedrooms (south rear), keeping functions in correct Vastu zones despite the narrow width",
      "Introduce a narrow internal light well or slot skylight in the middle third of the plan to prevent the Brahmasthan zone from becoming dark and stagnant",
      "Use the full 20 ft width for each room rather than creating a central corridor — a side-access staircase along the east or west boundary wall preserves usable floor area",
    ],
    category: "shape",
  },
];

// ─── COMBINED EXPORT ──────────────────────────────────────────────────────────
export const ALL_PRESETS = [...VASTU_PRESETS, ...ARCHETYPES, ...PLOT_SHAPES];
